version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: galerebuddy_postgres
    env_file:
      - ./.env
    ports:
      - "${DEVELOPMENT_DATABASE_HOST_PORT}:${DEVELOPMENT_DATABASE_CONTAINER_PORT}"
    environment:
      POSTGRES_USER: ${DEVELOPMENT_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEVELOPMENT_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEVELOPMENT_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: